from typing import List, TypedDict
from langchain_core.documents import Document

class GraphState(TypedDict):
    """
    Represents the state of our graph.
    
    Attributes:
        question: The user's original or rewritten question.
        generation: The final answer generated by the LLM.
        web_fallback: Boolean flag indicating if we need to search the web.
        documents: List of retrieved Document objects.
    """
    question: str
    generation: str
    web_fallback: bool
    documents: List[Document]